apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres-master
spec:
  replicas: 1  #only one is allowed
  template:
    metadata:
      labels:
        name: postgres
        role: master
    spec:
      containers:
        - name: postgres
          image: msiegenthaler/postgres-kubernetes:9.5
          ports:
            - name: transport
              containerPort: 5432
          volumeMounts:
            - name: postgres-data-storage
              mountPath: /var/lib/postgresql/data
            - name: credentials
              mountPath: /etc/postgres-credentials
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          livenessProbe:
            exec:
              command:
              - pg_isready
              - -h
              - localhost
              - -U
              - postgres
            initialDelaySeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            exec:
              command:
              - pg_isready
              - -h
              - localhost
              - -U
              - postgres
      volumes:
        - name: credentials
          secret:
            secretName: postgres-credentials
        - name: postgres-data-storage
          persistentVolumeClaim:
            claimName: postgres-data-storage
